### ISSUE TITLE
Pore Server Crash

### ISSUE THREAD

**Issue by alothmanmoe** [Maxqia/PoreRT#14]
Hey, so while using pore on my server a little bit ago i was using world edit and then the server crashed,
here is the crash report, im not sure if its from pore or something else but from looking at the first few lines it looks like its from pore.
http://pastebin.com/EFgzca01

**Comment by Maxqia** [comment]
looks like you did /top and it crashed, anyways I think I fixed it, gimmie a few minutes

**Comment by alothmanmoe** [comment]
all right
