### ISSUE TITLE
Double Jump Plugins

### ISSUE THREAD

**Issue by GershonR** [Maxqia/PoreRT#15]
These seem to be working fine without errors, the issue is these plugins depend on turning on fly mode for the player, changing the velocity, turning off fly and waiting for a player to hit a block.

The problem is that once flight is turned on, it won't turn off until a player flies onto a block,  the timer for turning it off automatically doesn't seem to work.

I tried these plugins:
https://dev.bukkit.org/projects/double-jump
https://dev.bukkit.org/projects/hub-double-jump

**Comment by Maxqia** [comment]
Hmm, that seems to be because PorePlayer.of(Player) != PorePlayer.of(Player) which screws up anything trying to store it.

**Comment by Maxqia** [comment]
-_- also that PlayerToggle(Flight, Sprint, and Sneak)Event isn't implemented

**Comment by Maxqia** [comment]
Fixed by fa4359c and efa1491 for my old plugin (Double Jump Minus). The plugins you listed were too old or not open source, so I didn't test using them.

**Comment by GershonR** [comment]
Awesome! Can you you add Double Jump Minus to the statues of plugins?

**Comment by Maxqia** [comment]
Added it

**Comment by GershonR** [comment]
Getting: http://pastebin.com/kGYcbqeS

On startup

spongeforge-1.10.2-2171-5.1.0-BETA-2010
Forge 12.18.2.2171

**Comment by Maxqia** [comment]
:/ don't have it backported for 1.10

**Comment by GershonR** [comment]
Pore is 1.11?
