### ISSUE TITLE
Error  plugins from bukkit

### ISSUE THREAD

**Issue by comdarksider** [Maxqia/PoreRT#2]
Error in spongeforge-1.10.2-API5.0-2092-1758
Worldguard from bukkit not working normal.

link error message : http://pastebin.com/nKF3g4Z73

**Comment by mbax** [comment]
@comdarksider the paste is gone ;)

**Comment by Maxqia** [comment]
It has an extra 3 at the end ...

**Comment by Maxqia** [comment]
Dupe of #13
