### ISSUE TITLE
a bug with chatevent

### ISSUE THREAD

**Issue by CyberSpongie** [Maxqia/PoreRT#23]
here a screenshot that shows that problem https://gyazo.com/ea861c56e714c6c54741e252d54ddf94
_**how to reproduce the error**_: get Permission base plugin like LuckPerms sponge plugin and get chat system like Nucleus and setup an rank with prefix talk in chat and you will see that it does not show your prefix 
as you see i tried typing in chat `a` and no prefix and it next to very close to my name
i had no plugins in my plugin folder so i know it's nothing to do with it, i had took out PoreRT and the prefix chat system went back to normal

**Comment by Maxqia** [comment]
0-0 does that prefix have no space in it normally?

**Comment by Maxqia** [comment]
Anyways 4be5fbae676faa42cb804759aedc594774e44dcb should've fixed it

**Comment by CyberSpongie** [comment]
Thanks it's fixed,
