### ISSUE TITLE
Cannot Run on 1.12.0:Duplicate mods

### ISSUE THREAD

**Issue by Hikari1nVoid** [Maxqia/PoreRT#35]
The crash report indicated that there are two same mods in this jarfie then crashed.

**Comment by Maxqia** [comment]
I'm not maintaining it anymore, haven't updated it to 1.12. It hooks into minecraft/sponge quite deeply, so you're probably SOL.

**Comment by Maxqia** [comment]
Try https://github.com/KettleFoundation/Kettle?
