### ISSUE TITLE
PoreRT for spongeforge 1.8.9 (api4)

### ISSUE THREAD

**Issue by Goddess324543** [Maxqia/PoreRT#39]
when trying to install [Build 120](https://github.com/Maxqia/PoreRT/releases/tag/jenkins120) an error appears:

net.minecraftforge.fml.common.MissingModsException: Mod pore (PoreRT) requires [spongeapi@6.0.0-SNAPSHOT]
Missing Mods:
        spongeapi : 6.0.0-SNAPSHOT

at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:238) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:492) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112) ~[ko.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

help

**Comment by Maxqia** [comment]
Hey, yea, you need to use a build from the [api4](https://github.com/Maxqia/PoreRT/tree/api4) branch.
Build 120 is for 1.11 iirc.
I think I lost any copies I have, so maybe you could try building it yourself. lmk if it still works.

**Comment by Goddess324543** [comment]
Unfortunately, this does not work, the error is:

:generateMetadata
:findGit
Using git version 2.30.0.windows.2 for patching submodule lib/Bukkit.
:updateSubmodules UP-TO-DATE
:applyPatches
Resetting C:\test\PoreRT\Porekit...
Applying patches from C:\test\PoreRT\patches to C:\test\PoreRT\Porekit
:applyPatches FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applyPatches'.
> Process returned error code. Expression: (result == 0). Values: result = 128

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by Maxqia** [comment]
I tried building the latest api4 version myself (it was quite difficult) and you can find it [here](https://github.com/Maxqia/PoreRT/files/6686335/PoreRT-1.0.0-backport-newbuild.zip), give it a try. If it doesn't work [this](https://github.com/Maxqia/PoreRT/files/6686317/PoreRT-1.0.0-backport.zip) is a old version I found on my computer. It should be compiled from ae736c29c759c3e97419bde566261a948eb8d5f9.
EDIT: I compiled the api5 branch for 1.10 [here](https://github.com/Maxqia/PoreRT/files/6686439/PoreRT-1.0.0-backport-1.10.zip)

By the way, what brings you into using PoreRT on 1.8.9? I'd like to know.

**Comment by Goddess324543** [comment]
I wanted to put NeoTech on one of my servers, this mod is in a stable version only for 1.8.9
and forge + bukkit on 1.8.9 is not present, PoreRT is the only thing that I found

**Comment by Goddess324543** [comment]
Thank you so much, it really works, you can say it made my dream come true!

**Comment by Goddess324543** [comment]
@Maxqia, Which tab change plugin should I use? [Tab](https://www.spigotmc.org/resources/tab-1-5-x-1-17-free-version.57806/) and [TitleManager](https://www.spigotmc.org/resources/titlemanager.1049/) not working

**Comment by Maxqia** [comment]
Hey, uh, yea, PoreRT is far from finished and it'd be way too much effort for me to complete it as it currently is. I don't think you'd find one that works with it at all if it currently doesn't work.

**Comment by Goddess324543** [comment]
How did you manage to compile PoreRT on 1.8.9?

**Comment by Maxqia** [comment]
Oh, okay I built mine on Arch Linux, because that's where I dev too. I also had a weird problem where I was getting 50x errors from the sponge powered maven server, because gradle was trying to download the sponge api from the http server & the maven server was sending 50x codes on the http version for some reason. I had to make a local proxy server & used /etc/hosts  to proxy http -> https for that server so it could download everything and build it.

**Comment by dimadencep** [comment]
Some plugins worked incorrectly or did not work on porert, I already tried to port craftbukkit 1.8.9 to forge, but today I thought, maybe you have craftbukkit rewritten for forge?

**Comment by dimadencep** [comment]
@Maxqia Вы работали с https://github.com/agaricusb/MinecraftRemapping ?

**Comment by dimadencep** [comment]
@Maxqia did you work with https://github.com/agaricusb/MinecraftRemapping ?
