### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by runescapejon** [Maxqia/PoreRT#7]
hey i had an randomtp plugin reason for this cause it has more feature with this plugin then an normal sponge one but anyways the plugin works fine but if you keep doing the /rtp command it will bring an error in console and unable to run the command again http://pastebin.com/NrQmJEsM
this happen random

**Comment by Maxqia** [comment]
It seems like it encountered a modded block and wasn't able convert it into a bukkit one ... (bukkit doesn't really support modded blocks)

**Comment by runescapejon** [comment]
oh okay thanks i'll guess ill look into another one or some sort thanks

**Comment by Maxqia** [comment]
I'll probably fix it in terms of that it'll pretend it's a stone block....

**Comment by runescapejon** [comment]
Thanks
