### ISSUE TITLE
Skript ?

### ISSUE THREAD

**Issue by CyberSpongie** [Maxqia/PoreRT#8]
Hello thanks you for updating this very grateful
i was wondering if you can get this plugin to fully work and supported it's called skript plugin from bukkit and it's an useful plugin for those who really have no idea how to code java so this plugin can use simple words to make an command for example

example:
`command /discord:
	trigger:
		send "&b&lDSICORD LINK:"
		send "==========LINK example==========="`

this simple skript command will basically send the user who run the command that message
very useful and it has other advanced feature like creating you own inventory gui command without coding java, but anyways if you can get this working thanks you
here the bukkit page
bukkit: https://dev.bukkit.org/bukkit-plugins/skript/
and here the continuation of it https://github.com/bensku/Skript

Thanks

**Comment by Maxqia** [comment]
I'm not sure if it'll ever work perfectly, but it should work somewhat. You can test it and if there's any errors/problems with it, you may tell me here.

**Comment by CyberSpongie** [comment]
i don't see any error's but the command discord one don't work at all 
when i tried it on spigot (non modded) it works

**Comment by Maxqia** [comment]
\*loads up skript on sponge\* \*sees huge error on startup\* You sure? Anyways the error looks like it's calling a Spigot API-only method so... that's gonna take a bit

**Comment by CyberSpongie** [comment]
http://pastebin.com/qEtaX63i

**Comment by Maxqia** [comment]
Please test again with the 1.11 version of PoreRT, there should be a lot more implementation for it

**Comment by skmedix** [comment]
@Maxqia  I'll make an issue with list of all the features (which are working, and which not). Just give me few days.

**Comment by CyberSpongie** [comment]
can you backport this to 1.10 ?

**Comment by GershonR** [comment]
A good alternative to Skript would be Denizen which is way more powerful and is currently being ported to Sponge

**Comment by CyberSpongie** [comment]
Yea but it's not simple and easy like skript

**Comment by Maxqia** [comment]
Superseeded by #20
